version: "3"
services:
  backend:
    restart: always
#    build: .
    image: marcosav/recommender-store-server
    container_name: recommender-store-server
    depends_on:
      - postgres
    ports:
      - "8080:80"
    env_file:
      - backend.env
#    volumes:
#    - ./product_dataset:/app/product_dataset
  postgres:
    restart: always
    image: postgres:alpine
    container_name: store-db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - postgres.env
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx_config_extension.conf:/etc/nginx/conf.d/nginx_config_extension.conf
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    depends_on:
      - backend
  letsencrypt:
    restart: always
    container_name: letsencrypt
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - nginx-proxy
volumes:
  database:
  html:
  certs:
  vhost:
  acme:
  conf: